services:

  db:
    image: postgres:15

    container_name: dr-postgres

    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:

    build: .

    container_name: dr-app

    environment:
      DB_HOST: db

    depends_on:
      - db

    ports:
      - "8000:8000"
